[2024-05-16 14:27:21,169: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-16 14:27:21,171: ERROR: stage_01_data_ingestion: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "D:\Projects\Stock_Market_Predictor_ETE\src\stock_predictor\pipeline\stage_01_data_ingestion.py", line 25, in <module>
    obj.main()
  File "D:\Projects\Stock_Market_Predictor_ETE\src\stock_predictor\pipeline\stage_01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Stock_Market_Predictor_ETE\src\stock_predictor\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pr141\PycharmProjects\pythonProject\venv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Stock_Market_Predictor_ETE\src\stock_predictor\utils\common.py", line 35, in read_yaml
    raise e
  File "D:\Projects\Stock_Market_Predictor_ETE\src\stock_predictor\utils\common.py", line 28, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2024-05-16 14:28:33,188: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-16 14:28:33,188: ERROR: stage_01_data_ingestion: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "D:\Projects\Stock_Market_Predictor_ETE\src\stock_predictor\pipeline\stage_01_data_ingestion.py", line 25, in <module>
    obj.main()
  File "D:\Projects\Stock_Market_Predictor_ETE\src\stock_predictor\pipeline\stage_01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Stock_Market_Predictor_ETE\src\stock_predictor\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pr141\PycharmProjects\pythonProject\venv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Stock_Market_Predictor_ETE\src\stock_predictor\utils\common.py", line 35, in read_yaml
    raise e
  File "D:\Projects\Stock_Market_Predictor_ETE\src\stock_predictor\utils\common.py", line 28, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
